import type { Component } from 'vue'
import {
  Ambulance,
  Apple,
  Baby,
  BadgeDollarSign,
  BadgePercent,
  Banknote,
  Beef,
  Bike,
  BookOpen,
  Box,
  BriefcaseBusiness,
  Building,
  BusFront,
  Calendar,
  Camera,
  Car,
  CarTaxiFront,
  ChartColumnIncreasing,
  ChartPie,
  ChefHat,
  CircleDollarSign,
  Coffee,
  Coins,
  CookingPot,
  CreditCard,
  CupSoda,
  Dog,
  Droplets,
  Dumbbell,
  Film,
  Flame,
  Fuel,
  Gamepad2,
  Gift,
  GraduationCap,
  Hammer,
  HandCoins,
  HandHeart,
  Heart,
  HeartPulse,
  Home,
  Hospital,
  Hotel,
  House,
  HouseHeart,
  Landmark,
  Laptop,
  Leaf,
  Lightbulb,
  Music,
  Package,
  Paintbrush,
  ParkingMeter,
  PartyPopper,
  PawPrint,
  PiggyBank,
  Pill,
  Pizza,
  Plane,
  Plug,
  Receipt,
  ReceiptText,
  Repeat,
  Route,
  School,
  Scissors,
  ShieldCheck,
  Shirt,
  ShoppingBasket,
  ShoppingCart,
  Smartphone,
  Sofa,
  Sparkles,
  Stethoscope,
  Tag,
  Ticket,
  TrainFront,
  TrendingDown,
  TrendingUp,
  Tv,
  Umbrella,
  User,
  Users,
  Utensils,
  Wallet,
  Wifi,
  Wrench,
  Zap,
} from '@lucide/vue'

export interface CategoryIconOption {
  id: string
  label: string
  group: string
  search: string
  component: Component
}

export const categoryIcons: CategoryIconOption[] = [
  { id: 'tag', label: 'General', group: 'Base', search: 'general varios categoria etiqueta otro', component: Tag },
  { id: 'sparkles', label: 'Extra', group: 'Base', search: 'extra especial varios mucho otros', component: Sparkles },
  { id: 'user', label: 'Persona', group: 'Base', search: 'persona personal miembro papa mama hijo', component: User },
  { id: 'users', label: 'Familia', group: 'Base', search: 'familia hogar compartido todos casa', component: Users },
  { id: 'calendar', label: 'Meses', group: 'Base', search: 'mes mensual fecha calendario corte msi', component: Calendar },
  { id: 'repeat', label: 'Recurrente', group: 'Base', search: 'suscripcion recurrente repetir mensual compromiso', component: Repeat },

  { id: 'utensils', label: 'Comida', group: 'Comida', search: 'comida restaurante comida preparada alimentos', component: Utensils },
  { id: 'shopping-cart', label: 'Super', group: 'Comida', search: 'super supermercado despensa compras mandado', component: ShoppingCart },
  { id: 'shopping-basket', label: 'Despensa', group: 'Comida', search: 'despensa mercado canasta abarrotes', component: ShoppingBasket },
  { id: 'cooking-pot', label: 'Cocina', group: 'Comida', search: 'cocina olla preparar alimentos', component: CookingPot },
  { id: 'chef-hat', label: 'Restaurante', group: 'Comida', search: 'restaurante comida fuera cena comida preparada', component: ChefHat },
  { id: 'coffee', label: 'Cafe', group: 'Comida', search: 'cafe cafeteria desayuno bebida', component: Coffee },
  { id: 'cup-soda', label: 'Antojos', group: 'Comida', search: 'antojitos bebidas refresco snack', component: CupSoda },
  { id: 'beef', label: 'Proteina', group: 'Comida', search: 'carne proteina pollo pescado', component: Beef },
  { id: 'apple', label: 'Fruta', group: 'Comida', search: 'fruta verdura saludable mercado', component: Apple },
  { id: 'pizza', label: 'Pizza', group: 'Comida', search: 'pizza comida rapida delivery', component: Pizza },

  { id: 'house', label: 'Casa', group: 'Hogar', search: 'casa renta vivienda hogar', component: House },
  { id: 'home', label: 'Hogar', group: 'Hogar', search: 'hogar casa familia vivienda', component: Home },
  { id: 'house-heart', label: 'Cuidado casa', group: 'Hogar', search: 'cuidado casa hogar familia', component: HouseHeart },
  { id: 'building', label: 'Departamento', group: 'Hogar', search: 'departamento edificio condominio oficina', component: Building },
  { id: 'landmark', label: 'Hipoteca', group: 'Hogar', search: 'banco hipoteca renta prestamo inmueble', component: Landmark },
  { id: 'bolt', label: 'Servicios', group: 'Hogar', search: 'servicios electricidad luz energia bolt', component: Zap },
  { id: 'flame', label: 'Gas', group: 'Hogar', search: 'gas fuego estacionario lp', component: Flame },
  { id: 'droplets', label: 'Agua', group: 'Hogar', search: 'agua consumo servicio gotas', component: Droplets },
  { id: 'wifi', label: 'Internet', group: 'Hogar', search: 'internet wifi modem red', component: Wifi },
  { id: 'plug', label: 'Luz', group: 'Hogar', search: 'luz enchufe electricidad servicio', component: Plug },
  { id: 'lightbulb', label: 'Focos', group: 'Hogar', search: 'focos luz lamparas energia', component: Lightbulb },
  { id: 'wrench', label: 'Mantenimiento', group: 'Hogar', search: 'mantenimiento reparar arreglo herramienta', component: Wrench },
  { id: 'hammer', label: 'Reparaciones', group: 'Hogar', search: 'reparacion obra arreglo martillo', component: Hammer },
  { id: 'paintbrush', label: 'Mejoras', group: 'Hogar', search: 'pintura remodelacion mejoras casa', component: Paintbrush },
  { id: 'scissors', label: 'Servicios casa', group: 'Hogar', search: 'servicios limpieza corte arreglo', component: Scissors },
  { id: 'sofa', label: 'Muebles', group: 'Hogar', search: 'muebles sala sofa decoracion', component: Sofa },
  { id: 'package', label: 'Bodega', group: 'Hogar', search: 'bodega paquete caja almacen', component: Package },
  { id: 'box', label: 'Caja', group: 'Hogar', search: 'caja bodega almacen paquete box', component: Box },
  { id: 'leaf', label: 'Jardin', group: 'Hogar', search: 'jardin plantas patio', component: Leaf },

  { id: 'car', label: 'Auto', group: 'Transporte', search: 'auto coche carro transporte', component: Car },
  { id: 'fuel', label: 'Gasolina', group: 'Transporte', search: 'gasolina combustible auto gas', component: Fuel },
  { id: 'parking-meter', label: 'Estacionamiento', group: 'Transporte', search: 'estacionamiento parking parquimetro', component: ParkingMeter },
  { id: 'taxi', label: 'Taxi', group: 'Transporte', search: 'taxi uber didi viaje coche', component: CarTaxiFront },
  { id: 'bus', label: 'Autobus', group: 'Transporte', search: 'autobus camion transporte publico', component: BusFront },
  { id: 'train', label: 'Metro', group: 'Transporte', search: 'metro tren transporte publico', component: TrainFront },
  { id: 'bike', label: 'Bici', group: 'Transporte', search: 'bicicleta bici transporte ejercicio', component: Bike },
  { id: 'route', label: 'Traslados', group: 'Transporte', search: 'ruta traslado viaje camino', component: Route },
  { id: 'plane', label: 'Viajes', group: 'Transporte', search: 'viaje avion vacaciones vuelo', component: Plane },
  { id: 'hotel', label: 'Hotel', group: 'Transporte', search: 'hotel hospedaje viaje vacaciones', component: Hotel },

  { id: 'heart', label: 'Salud', group: 'Salud', search: 'salud bienestar yoga corazon', component: Heart },
  { id: 'heart-pulse', label: 'Medico', group: 'Salud', search: 'medico salud pulso bienestar', component: HeartPulse },
  { id: 'pill', label: 'Medicinas', group: 'Salud', search: 'medicina medicinas farmacia pastillas', component: Pill },
  { id: 'stethoscope', label: 'Consulta', group: 'Salud', search: 'doctor consulta medico estetoscopio', component: Stethoscope },
  { id: 'hospital', label: 'Hospital', group: 'Salud', search: 'hospital clinica emergencia', component: Hospital },
  { id: 'ambulance', label: 'Emergencia', group: 'Salud', search: 'emergencia ambulancia urgencias', component: Ambulance },
  { id: 'dumbbell', label: 'Ejercicio', group: 'Salud', search: 'ejercicio gimnasio deporte pesas yoga', component: Dumbbell },
  { id: 'hand-heart', label: 'Cuidado', group: 'Salud', search: 'cuidado apoyo familia ayuda salud', component: HandHeart },

  { id: 'piggy-bank', label: 'Ahorro', group: 'Finanzas', search: 'ahorro cochinito guardar dinero', component: PiggyBank },
  { id: 'wallet', label: 'Cartera', group: 'Finanzas', search: 'cartera efectivo disponible dinero', component: Wallet },
  { id: 'credit-card', label: 'Tarjeta', group: 'Finanzas', search: 'tarjeta credito debito pago', component: CreditCard },
  { id: 'receipt', label: 'Recibo', group: 'Finanzas', search: 'recibo ticket comprobante gasto', component: Receipt },
  { id: 'receipt-text', label: 'Deudas', group: 'Finanzas', search: 'deuda recibo pago factura pendiente', component: ReceiptText },
  { id: 'hand-coins', label: 'Ingresos', group: 'Finanzas', search: 'ingreso cobro sueldo monedas', component: HandCoins },
  { id: 'banknote', label: 'Efectivo', group: 'Finanzas', search: 'efectivo billete dinero cash', component: Banknote },
  { id: 'coins', label: 'Monedas', group: 'Finanzas', search: 'monedas cambio efectivo dinero', component: Coins },
  { id: 'circle-dollar-sign', label: 'Dinero', group: 'Finanzas', search: 'dinero presupuesto pago dolar peso', component: CircleDollarSign },
  { id: 'badge-dollar-sign', label: 'Pago', group: 'Finanzas', search: 'pago cargo cuota dinero', component: BadgeDollarSign },
  { id: 'chart-pie', label: 'Presupuesto', group: 'Finanzas', search: 'presupuesto grafica analitica plan', component: ChartPie },
  { id: 'chart-up', label: 'Tendencia', group: 'Finanzas', search: 'tendencia progreso incremento grafica', component: ChartColumnIncreasing },
  { id: 'trending-up', label: 'Sube', group: 'Finanzas', search: 'sube aumenta tendencia gasto', component: TrendingUp },
  { id: 'trending-down', label: 'Baja', group: 'Finanzas', search: 'baja disminuye ahorro gasto', component: TrendingDown },
  { id: 'badge-percent', label: 'Descuento', group: 'Finanzas', search: 'descuento promocion porcentaje oferta', component: BadgePercent },
  { id: 'shield-check', label: 'Seguro', group: 'Finanzas', search: 'seguro proteccion garantia', component: ShieldCheck },
  { id: 'umbrella', label: 'Emergencias', group: 'Finanzas', search: 'emergencia fondo proteccion lluvia', component: Umbrella },

  { id: 'graduation-cap', label: 'Educacion', group: 'Vida diaria', search: 'educacion escuela universidad cursos', component: GraduationCap },
  { id: 'book-open', label: 'Libros', group: 'Vida diaria', search: 'libros cursos lectura estudio', component: BookOpen },
  { id: 'school', label: 'Escuela', group: 'Vida diaria', search: 'escuela colegio clases educacion', component: School },
  { id: 'briefcase', label: 'Trabajo', group: 'Vida diaria', search: 'trabajo oficina negocio profesion', component: BriefcaseBusiness },
  { id: 'laptop', label: 'Tecnologia', group: 'Vida diaria', search: 'tecnologia laptop computadora equipo', component: Laptop },
  { id: 'smartphone', label: 'Celular', group: 'Vida diaria', search: 'celular telefono movil smartphone', component: Smartphone },
  { id: 'tv', label: 'TV', group: 'Vida diaria', search: 'television streaming pantalla entretenimiento', component: Tv },
  { id: 'baby', label: 'Bebe', group: 'Vida diaria', search: 'bebe hijos ninos familia', component: Baby },
  { id: 'paw', label: 'Mascotas', group: 'Vida diaria', search: 'mascotas perro gato paw perros', component: PawPrint },
  { id: 'dog', label: 'Perros', group: 'Vida diaria', search: 'perros mascota perro veterinario', component: Dog },
  { id: 'shirt', label: 'Ropa', group: 'Vida diaria', search: 'ropa vestido zapatos moda', component: Shirt },
  { id: 'gift', label: 'Regalos', group: 'Vida diaria', search: 'regalo cumpleanos fiesta detalle', component: Gift },

  { id: 'gamepad', label: 'Juegos', group: 'Ocio', search: 'juegos videojuegos entretenimiento', component: Gamepad2 },
  { id: 'film', label: 'Cine', group: 'Ocio', search: 'cine pelicula entretenimiento', component: Film },
  { id: 'music', label: 'Musica', group: 'Ocio', search: 'musica concierto audio', component: Music },
  { id: 'ticket', label: 'Boletos', group: 'Ocio', search: 'boletos eventos entradas cine concierto', component: Ticket },
  { id: 'party-popper', label: 'Fiesta', group: 'Ocio', search: 'fiesta celebracion evento cumpleanos', component: PartyPopper },
  { id: 'camera', label: 'Fotos', group: 'Ocio', search: 'fotos fotografia recuerdos camara', component: Camera },
]

const iconMap = new Map(categoryIcons.map((icon) => [icon.id, icon]))

export function normalizeCategoryIconId(icon?: string | null) {
  const value = icon?.trim()
  if (!value) return categoryIcons[0].id
  if (iconMap.has(value)) return value
  const withoutLucidePrefix = value.startsWith('lucide:') ? value.slice('lucide:'.length) : value
  if (iconMap.has(withoutLucidePrefix)) return withoutLucidePrefix
  return categoryIcons[0].id
}

export function getCategoryIcon(icon?: string | null) {
  return iconMap.get(normalizeCategoryIconId(icon)) ?? categoryIcons[0]
}
