# Generated by Django 5.2.13 on 2026-04-20 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='category',
            name='unique_category_by_scope_member',
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(condition=models.Q(('scope', 'global')), fields=('name',), name='unique_global_category_name'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(condition=models.Q(('scope', 'personal')), fields=('name', 'member'), name='unique_personal_category_name'),
        ),
    ]
