# Generated by Django 5.2.13 on 2026-04-20 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_remove_category_unique_category_by_scope_member_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('cash', 'Efectivo'), ('bank', 'Banco'), ('debit_card', 'Tarjeta de debito'), ('credit_card', 'Tarjeta de credito')], max_length=24),
        ),
    ]
