# Generated by Django 5.2.13 on 2026-04-20 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_alter_account_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='merchant',
            field=models.CharField(blank=True, max_length=160),
        ),
    ]
