# Generated by Codex on 2026-04-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0004_transaction_merchant"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="icon",
            field=models.CharField(default="tag", max_length=40),
        ),
    ]
