# Generated by Codex on 2026-04-21

from django.db import migrations, models
from django.utils import timezone


def normalize_name(value):
    return " ".join(value.strip().split())


def lookup_key(value):
    return normalize_name(value).casefold()


def backfill_merchant_concepts(apps, schema_editor):
    Transaction = apps.get_model("budget", "Transaction")
    MerchantConcept = apps.get_model("budget", "MerchantConcept")
    counts = {}
    names = {}
    for merchant in (
        Transaction.objects.filter(transaction_type="expense")
        .exclude(merchant="")
        .values_list("merchant", flat=True)
    ):
        clean_name = normalize_name(merchant)
        if not clean_name:
            continue
        key = lookup_key(clean_name)
        counts[key] = counts.get(key, 0) + 1
        names.setdefault(key, clean_name)

    now = timezone.now()
    for key, count in counts.items():
        concept, created = MerchantConcept.objects.get_or_create(
            normalized_name=key,
            defaults={
                "name": names[key],
                "usage_count": count,
                "last_used_at": now,
            },
        )
        if not created:
            concept.usage_count += count
            concept.last_used_at = now
            concept.save(update_fields=["usage_count", "last_used_at", "updated_at"])


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0005_category_icon"),
    ]

    operations = [
        migrations.CreateModel(
            name="MerchantConcept",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=160)),
                ("normalized_name", models.CharField(db_index=True, max_length=160, unique=True)),
                ("usage_count", models.PositiveIntegerField(default=0)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-usage_count", "name"],
            },
        ),
        migrations.RunPython(backfill_merchant_concepts, migrations.RunPython.noop),
    ]
