# Generated by Django 5.2.13 on 2026-04-21 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0008_invitation_names_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='installmentplan',
            name='first_payment_number',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
