# Generated by Django 5.2.13 on 2026-04-21 19:53

from django.db import migrations, models
from django.utils import timezone


def normalize_name(value):
    return " ".join((value or "").strip().split())


def lookup_key(value):
    return normalize_name(value).casefold()


def record_concept(MerchantConcept, name):
    clean_name = normalize_name(name)
    if not clean_name:
        return
    concept, created = MerchantConcept.objects.get_or_create(
        normalized_name=lookup_key(clean_name),
        defaults={"name": clean_name},
    )
    if created:
        concept.usage_count = 1
    else:
        concept.usage_count += 1
    concept.last_used_at = timezone.now()
    concept.save(update_fields=["usage_count", "last_used_at", "updated_at"])


def backfill_commitment_merchants(apps, schema_editor):
    RecurringExpense = apps.get_model("budget", "RecurringExpense")
    InstallmentPlan = apps.get_model("budget", "InstallmentPlan")
    MerchantConcept = apps.get_model("budget", "MerchantConcept")

    for recurring in RecurringExpense.objects.filter(merchant=""):
        recurring.merchant = normalize_name(recurring.name)
        recurring.save(update_fields=["merchant"])
        record_concept(MerchantConcept, recurring.merchant)

    for plan in InstallmentPlan.objects.filter(merchant=""):
        plan.merchant = normalize_name(plan.name)
        plan.save(update_fields=["merchant"])
        record_concept(MerchantConcept, plan.merchant)


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0009_installmentplan_first_payment_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='installmentplan',
            name='merchant',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='recurringexpense',
            name='merchant',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.RunPython(backfill_commitment_merchants, migrations.RunPython.noop),
    ]
