# Generated by Django 5.2.9 on 2026-04-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0010_installmentplan_merchant_recurringexpense_merchant"),
    ]

    operations = [
        migrations.AddField(
            model_name="installmentplan",
            name="round_up_monthly_payment",
            field=models.BooleanField(default=False),
        ),
    ]
