# Generated by Codex on 2026-04-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0011_installmentplan_round_up_monthly_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="installmentplan",
            name="round_up_monthly_payment",
            field=models.BooleanField(default=True),
        ),
    ]
