# Generated by Django 5.2.13 on 2026-04-21 22:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0012_alter_installmentplan_round_up_monthly_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='budget_behavior',
            field=models.CharField(choices=[('monthly_reset', 'Se reinicia cada mes'), ('carryover', 'Acumula saldo')], default='monthly_reset', max_length=24),
        ),
        migrations.AddField(
            model_name='category',
            name='carryover_initial_balance_cents',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='category',
            name='carryover_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='overspend_tracking_start_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.CreateModel(
            name='CategoryBudgetChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_cents', models.PositiveIntegerField()),
                ('effective_date', models.DateField()),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_changes', to='budget.category')),
            ],
            options={
                'ordering': ['category__name', 'period_start', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='CategoryOverspendRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('budget_cents', models.PositiveIntegerField(default=0)),
                ('spent_cents', models.PositiveIntegerField(default=0)),
                ('overspend_cents', models.PositiveIntegerField(default=0)),
                ('recorded_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overspend_records', to='budget.category')),
            ],
            options={
                'ordering': ['category__name', '-period_start'],
                'constraints': [models.UniqueConstraint(fields=('category', 'period_start', 'period_end'), name='unique_category_overspend_period')],
            },
        ),
    ]
