# Generated by Django 5.2.13 on 2026-05-30

import budget.timezones
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0015_category_budget_treatment"),
    ]

    operations = [
        migrations.AddField(
            model_name="appsettings",
            name="time_zone",
            field=models.CharField(default=budget.timezones.default_app_time_zone, max_length=64),
        ),
        migrations.AlterField(
            model_name="category",
            name="overspend_tracking_start_date",
            field=models.DateField(default=budget.timezones.app_localdate),
        ),
    ]
