# Generated by Django 5.2.14 on 2026-07-01 23:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


def fill_credit_card_cutoffs(apps, schema_editor):
    Account = apps.get_model("budget", "Account")
    AppSettings = apps.get_model("budget", "AppSettings")
    global_cutoff = AppSettings.objects.values_list("cutoff_day", flat=True).first() or 20
    Account.objects.filter(account_type="credit_card").update(cutoff_day=global_cutoff)


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0016_appsettings_time_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='cutoff_day',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)]),
        ),
        migrations.AddField(
            model_name='account',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_accounts', to='budget.householdmember'),
        ),
        migrations.RunPython(fill_credit_card_cutoffs, migrations.RunPython.noop),
    ]
