# Generated by Django 5.2.14 on 2026-07-02 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0017_account_cutoff_day_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appsettings',
            name='cutoff_day',
        ),
    ]
