# Generated by Django 5.2.14 on 2026-07-18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0019_recalculate_calendar_periods"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="payment_due_day",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(31),
                ],
            ),
        ),
    ]
